# Ghost FFA configuration file!
#
# Do not change anything unless you know what you're doing!
#
# Also, anything changed in this file is immediately changed back as soon
# as the server restarts, so this file is mainly for debugging.

blockedCommands:
  bypassPermission: ghostffa.bypass.blockedcommands
  whitelisted:
    - 'duel'
    - 'spectate'
    - 'games'
    - 'discord'
    - 'ping'
    - 'kits'
    - 'k'
    - 'kit'
    - 'clearlag'
    - 'spawn'
builtInClearLag:
  interval: 600 # in seconds
  showConsoleMessages: true
  worldsCleared: ['world'] # case insensitive
join: # PlaceholderAPI works here
  - '{seperator}'
  - '&fWelcome to &b&lGhostFFA'
  - ' '
  - '&7&oYou have been away for {time}, welcome back :)'
  - '{seperator}'
invClickCooldown: 5 # in ticks
timeZone: 'GMT-4'
disabledKickMessages: # if a kick message contains this, it will not kick them for it
  - 'Kicked for spamming'
  - 'Illegal characters in chat'
chatCooldown: 1000 # in miliseconds